FROM registry.exness.io/service/collector/host:1.9.3.11-1.1.0


ADD ./collector /usr/local/bin/
ADD ./config.conf /
ADD ./dlv /usr/local/bin/

#RUN wget https://dl.google.com/go/go1.11.4.linux-amd64.tar.gz \
#&& tar -xvf go1.11.4.linux-amd64.tar.gz \
#&& mv go /usr/local \
#&& ln -s /usr/local/go/bin/go /usr/local/bin/go \
#&& rm -rf go1.11.4.linux-amd64.tar.gz
#ENV GOROOT=/usr/local/go
